### ISSUE TITLE
Add Zanne et al. and Werner et al. data to the distributed file

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/growthform#3]
Ideally the output would then be:

| Species        | Woody | N-fixing | Support |
|----------------|-------|----------|---------|
| Pinus poderosa | Y     | N        | F       | 
| Hedera helix   | Y     | N        | C       |

**Comment by wcornwell** [comment]
@dfalster @rachaelgallagher anything else that would be useful for this package to do?

**Comment by dfalster** [comment]
Nice work! 

C3 vs C4 could be good too.
